# Generated by Django 3.2.23 on 2023-12-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='closing_hour',
        ),
        migrations.RemoveField(
            model_name='post',
            name='opening_hour',
        ),
        migrations.AddField(
            model_name='post',
            name='closing_time',
            field=models.IntegerField(choices=[(0, '12am'), (1, '1am'), (2, '2am'), (3, '3am'), (4, '4am'), (5, '5am'), (6, '6am'), (7, '7am'), (8, '8am'), (9, '9am'), (10, '10am'), (11, '11am'), (12, '12pm'), (13, '1pm'), (14, '2pm'), (15, '3pm'), (16, '4pm'), (17, '5pm'), (18, '6pm'), (19, '7pm'), (20, '8pm'), (21, '9pm'), (22, '10pm'), (23, '11pm')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='opening_time',
            field=models.IntegerField(choices=[(0, '12am'), (1, '1am'), (2, '2am'), (3, '3am'), (4, '4am'), (5, '5am'), (6, '6am'), (7, '7am'), (8, '8am'), (9, '9am'), (10, '10am'), (11, '11am'), (12, '12pm'), (13, '1pm'), (14, '2pm'), (15, '3pm'), (16, '4pm'), (17, '5pm'), (18, '6pm'), (19, '7pm'), (20, '8pm'), (21, '9pm'), (22, '10pm'), (23, '11pm')], default=0),
        ),
    ]
