# Generated by Django 3.2.23 on 2023-12-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
