# Generated by Django 3.2.23 on 2023-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0002_auto_20231210_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategorised', max_length=30),
        ),
    ]
