# Generated by Django 3.2.23 on 2023-12-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0002_alter_post_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
